export const constantRoutes = [
  {
    path: '/dashboard',
    title: '仪表盘',
    icon: 'icon-fenxi',
    hidden: false,
    microNmae: 'qiankun-sub',
    microLink: '',
    type: 0,
    children: [
      {
        path: '/dashboard/analysis',
        title: '分析页',
        icon: 'icon-tongjifenxi',
        hidden: false,
        microNmae: 'qiankun-sub',
        microLink: '',
        type: 0,
      },
    ],
  },
  {
    path: '/example',
    title: '示例',
    icon: 'icon-igw-l-dashboard-rectangle-add',
    hidden: false,
    microNmae: 'qiankun-micro',
    microLink: '',
    type: 0,
    children: [
      {
        path: '/example/table',
        title: '表格',
        icon: 'icon-fuwenbenbianjiqi_biaoge',
        hidden: false,
        microNmae: 'qiankun-micro',
        microLink: '',
        type: 0,
      },
      {
        path: '/example/print',
        title: '打印',
        icon: 'icon-a-83-dayin',
        hidden: false,
        microNmae: 'qiankun-micro',
        microLink: '',
        type: 0,
      },
    ],
  },
  {
    path: '/system-setting',
    title: '系统设置',
    icon: 'icon-igw-l-dashboard-rectangle-add',
    hidden: false,
    microNmae: 'qiankun-sub',
    microLink: '',
    type: 0,
    children: [
      {
        path: '/system-setting/personnel',
        title: '人员管理',
        icon: 'icon-fuwenbenbianjiqi_biaoge',
        hidden: false,
        microNmae: 'qiankun-sub',
        microLink: '',
        type: 0,
      },
    ],
  },
]
